name: Build Addon

# This workflow creates a usable addon zip for each commit.

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: BigWigsMods/packager@v2
        with:
          args: -d

      - name: debug
        run: |
          # ls -laR .release
          pwd && find .release

      - name: Upload build
        uses: actions/upload-artifact@v6
        with:
          name: ItemVersion
          include-hidden-files: true
          path: |
            .release/
            !.release/*.zip
