name: Build Addon

# This workflow creates a usable addon zip for each commit.

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      NEW_DIR: build-from-commit-artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: BigWigsMods/packager@v2
        with:
          args: -d

      - name: debug
        run: ls -laR .release

      - uses: actions/upload-artifact@v6
        with:
          name: ItemVersion
          path: .release/*
